### PR TITLE
`ROG CROSSHAIR VIII IMPACT`: Add support

### PR DESCRIPTION
**Pull request by mbana**
```sh
$ sensors
asus-wmi-ec-sensors-isa-0000
Adapter: ISA adapter
Chipset:     3916 RPM
Chipset:      +66.0°C
CPU:          +38.0°C
Motherboard:  +36.0°C
T_Sensor:     +28.0°C
VRM:          +44.0°C
CPU:           0.00 A
...
$ sudo dmidecode -t 2

# dmidecode 3.3
Getting SMBIOS data from sysfs.
SMBIOS 3.3.0 present.

Handle 0x0002, DMI type 2, 15 bytes
Base Board Information
	Manufacturer: ASUSTeK COMPUTER INC.
	Product Name: ROG CROSSHAIR VIII IMPACT
	Version: Rev X.0x
	Serial Number: <omitted>
	Asset Tag: Default string
	Features:
		Board is a hosting board
		Board is replaceable
	Location In Chassis: Default string
	Chassis Handle: 0x0003
	Type: Motherboard
	Contained Object Handles: 0
```

### CODE REVIEW

**Comment by mbana** [comment]
> Thank you! I would like to ask you for some additional information, please, that should help to mainline this driver.
> 
> 1. Could you, please, also provide the dump of the EC registers (`# hexdump -C /sys/kernel/debug/ec/ec0/io` after loading the ec_sys kernel module)?
> 2. How much time does it take on your system to read EC registers? (`time cat /sys/kernel/debug/ec/ec0/io > /dev/null`).
> 3. How much time does it take to update sensors? (`time sensors asus-wmi-ec-sensors-isa-0000` when EC registers are actually read, i.e. with a 1+ sec delay between `sensors` calls).
> 
> BTW, the [other driver](https://github.com/zeule/asus-ec-sensors) might work faster.

```sh
[root@mbana-pc2 ~]# cat /etc/os-release
NAME="Fedora Linux"
VERSION="35 (Workstation Edition)"
ID=fedora
VERSION_ID=35
VERSION_CODENAME=""
PLATFORM_ID="platform:f35"
PRETTY_NAME="Fedora Linux 35 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:35"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f35/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=35
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=35
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
[root@mbana-pc2 ~]# hexdump -C /sys/kernel/debug/ec/ec0/io
hexdump: /sys/kernel/debug/ec/ec0/io: No such file or directory
hexdump: all input file arguments failed
[root@mbana-pc2 ~]# time cat /sys/kernel/debug/ec/ec0/io > /dev/null
cat: /sys/kernel/debug/ec/ec0/io: No such file or directory

real	0m0.001s
user	0m0.000s
sys	0m0.001s
[root@mbana-pc2 ~]# time sensors asus-wmi-ec-sensors-isa-0000
Parse error in chip name `asus-wmi-ec-sensors-isa-0000'
Try `sensors -h' for more information

real	0m0.003s
user	0m0.001s
sys	0m0.002s
```

I am on Fedora 35 and I don't think the `ec_sys` module is available.

**Comment by zeule** [comment]
Thank you! As `sensors asus-wmi-ec-sensors-isa-0000` fails (don't know why), could you, please, measure the time to read all the available sensors via `time sensors`?

**Comment by zeule** [comment]
@mbana, I would also very much appreciate if you share, please, the DSDT code for the motherboard (`cat /sys/firmware/acpi/tables/DSDT`).

**Comment by mbana** [comment]
> @mbana, I would also very much appreciate if you share, please, the DSDT code for the motherboard (`cat /sys/firmware/acpi/tables/DSDT`).

`$ sudo cat /sys/firmware/acpi/tables/DSDT > rog-crosshair-viii-impact-model.DSDT`

is Attached.

[rog-crosshair-viii-impact-model.DSDT.txt](https://github.com/zeule/asus-wmi-ec-sensors/files/7602422/rog-crosshair-viii-impact-model.DSDT.txt)

**Comment by zeule** [comment]
Thanks a lot!

**Pull request merged**
